### ISSUE TITLE
Faltando informação nas rotas à API

### ISSUE THREAD

**Issue by felipejh** [Isabelarrodrigues/desafio-admin-web#2]
No arquivo README.md, na parte onde é listada as rotas à API, está falando uma informação nas rotas.
Está faltando `/api` após a porta.

Como está:
`http://localhost:3001/users`

Como é a rota configurada no Express:
`http://localhost:3001/api/users`

**Comment by lukascivil** [comment]
@felipejh Thx meu caro, estamos subindo o ajuste.
